rootProject.name = 'payment'
include 'payment-service'
include 'payment-service:payment-container'
include 'payment-service:payment-dataaccess'
include 'payment-service:payment-dataaccess'
include 'payment-service:payment-domain'
include 'payment-service:payment-domain:payment-application-service'
include 'payment-service:payment-domain:payment-domain-core'
include 'payment-service:payment-messaging'
include 'common'
include 'common:common-application'
include 'common:common-dataaccess'
include 'common:common-domain'
include 'infrastructure'
include 'infrastructure:kafka'
include 'infrastructure:kafka:kafka-config-data'
include 'infrastructure:kafka:kafka-consumer'
include 'infrastructure:kafka:kafka-model'
include 'infrastructure:kafka:kafka-producer'
include 'infrastructure:outbox'
include 'infrastructure:saga'
include 'payment-service:payment-application'